import {programme,fresh,complete,count,total,previous,recommendation,makeSession,finish,remaining,validate} from './model.js';
const KEY='form-workouts-v1';let state=fresh(),storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch{storageOK=false;}
let day=state.activeDay??state.nextDay,view='workout',audio,noticeTimeout;
const app=document.querySelector('#app'),timerEl=document.querySelector('#timer');
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
function notice(text){document.querySelector('#notice').textContent=text;clearTimeout(noticeTimeout);noticeTimeout=setTimeout(()=>document.querySelector('#notice').textContent='',6000);}
function save(){if(!storageOK){notice('Storage could not be read. Export a backup before importing or reloading.');return;}try{localStorage.setItem(KEY,JSON.stringify(state));}catch{notice('Your device could not save this change. Export a backup now.');}}
function session(){return state.drafts[day]??makeSession(state,day);}
function begin(){if(!state.drafts[day])state.drafts[day]=makeSession(state,day);state.activeDay=day;return state.drafts[day];}
function unlockAudio(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function alertRest(){try{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=740;g.gain.setValueAtTime(.15,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.65);o.start();o.stop(audio.currentTime+.7);}catch{}navigator.vibrate?.([200,100,200]);}
function startTimer(ex){const duration=state.settings.rest[ex.id]??ex.rest;state.timer={duration,remaining:duration,endsAt:Date.now()+duration*1000,paused:false,label:ex.name};save();renderTimer();}
let timerSignature='';
function renderTimer(){const t=state.timer;timerEl.hidden=!t;if(!t){timerSignature='';return;}const seconds=remaining(t),signature=t.label+'|'+t.paused+'|'+(seconds===0);if(signature===timerSignature){timerEl.querySelector('[role=timer]').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;return;}timerSignature=signature;timerEl.innerHTML=`<div class="timer-top"><span>${seconds===0?'Rest complete':t.paused?'Rest paused':'Rest timer'}<br><small style="color:#c9ded2">${esc(t.label)}</small></span><strong role="timer">${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}</strong></div><div class="actions"><button data-timer="pause">${t.paused?'Resume':'Pause'}</button><button data-timer="restart">Restart</button><button data-timer="add">+30 sec</button><button data-timer="dismiss">Dismiss</button></div>`;}
function renderWorkout(){const s=session();app.innerHTML=`<div class="eyebrow">Your programme · four-day split</div><h1>Day ${day+1}<span style="color:#9cac9f"> / 04</span></h1><div class="summary"><p class="muted">${state.drafts[day]?'Session in progress':'Ready when you are.'}</p><p class="muted">6 exercises · ${total(s)} working sets</p></div><div class="day-tabs" aria-label="Workout day">${programme.map((_,i)=>`<button data-day="${i}" class="${i===day?'active':''}" aria-pressed="${i===day}">Day ${i+1}</button>`).join('')}</div><div class="summary"><strong>${count(s)} of ${total(s)} sets complete</strong><small>Swipe to change day</small></div><div class="track"><span style="width:${count(s)/total(s)*100}%"></span></div>${s.exercises.map((ex,ei)=>{const prev=previous(state,ex.id);return `<section class="exercise"><div class="exercise-head"><span class="number">${String(ei+1).padStart(2,'0')}</span><div><h2>${ex.name}</h2><p class="muted">${programme[day][ei].sets} × ${ex.reps} reps${ex.unilateral?' per arm':''} <span aria-hidden="true">·</span> ${state.settings.rest[ex.id]??ex.rest}s rest</p></div></div>${prev?`<div class="recommendation">${recommendation(prev)==='increase'?'Next session: increase by your smallest available weight increment.':'Next session: retain your previous weight and build toward every rep.'}</div>`:''}<div class="set-grid labels"><span>SET</span><span style="text-align:center">KG</span><span style="text-align:center">REPS</span><span>DONE</span></div>${ex.sets.map((set,si)=>`<div class="set-block">${set.sides.map((a,ai)=>{const p=prev?.sets.filter(x=>!x.warmup)[si]?.sides[ai];return `<div class="set-grid"><span class="set-name">${set.warmup?'W':si+1}${ex.unilateral?`<br><small>${a.side}</small>`:''}</span><label><input aria-label="${ex.name} set ${si+1} ${a.side} weight in kilograms" type="number" inputmode="decimal" min="0" max="2000" step="0.25" placeholder="—" value="${a.weight}" data-field="weight" data-pos="${ei},${si},${ai}"><span class="previous">${p&&!set.warmup?`Prev ${p.weight===''?'—':p.weight} kg${p.done?'':' · not done'}`:'No previous'}</span></label><label><input aria-label="${ex.name} set ${si+1} ${a.side} reps" type="number" inputmode="numeric" min="0" max="1000" step="1" value="${a.reps}" data-field="reps" data-pos="${ei},${si},${ai}"><span class="previous">${p&&!set.warmup?`Prev ${p.reps} reps`:`Target ${ex.reps}`}</span></label><button class="${a.done?'done':''}" aria-label="${a.done?'Undo':'Complete'} ${ex.name} set ${si+1} ${a.side}" aria-pressed="${a.done}" data-complete="${ei},${si},${ai}">${a.done?'✓':'○'}</button></div>`;}).join('')}</div>`).join('')}<button class="warmup" data-warmup="${ei}">+ Add warm-up set</button></section>`;}).join('')}<button class="primary finish" id="finish">Finish Workout</button><p class="muted" style="text-align:center">Saved on this device. Every set counts.</p>`;}
function renderHistory(){app.innerHTML=`<div class="eyebrow">Your training log</div><h1>History</h1><p class="muted">${state.history.length} saved workout${state.history.length===1?'':'s'}</p>${state.history.length?state.history.map(s=>`<details class="card"><summary>Day ${s.day+1} · ${date(s.endedAt)}<span class="badge">${s.endedEarly?'Ended early':'Completed'}</span><br><small>${count(s)} / ${total(s)} working sets</small></summary>${s.exercises.map(e=>`<div class="history-ex"><h3>${e.name}</h3>${e.sets.map((set,i)=>`<p>${set.warmup?'Warm-up':`Set ${i+1}`} · ${set.sides.map(a=>`${e.unilateral?a.side+' ':''}${a.weight===''?'—':a.weight} kg × ${a.reps} reps · ${a.done?'Done':'Not completed'}`).join(' / ')}</p>`).join('')}</div>`).join('')}</details>`).join(''):'<p class="empty">Your first finished workout will appear here, including any sessions you finish early.</p>'}`;}
function renderProgress(){const list=programme.flat().map(ex=>{const records=state.history.filter(s=>s.exercises.some(e=>e.id===ex.id)).slice().reverse().map(s=>({date:s.endedAt,ex:s.exercises.find(e=>e.id===ex.id)}));const done=records.flatMap(r=>r.ex.sets.filter(s=>!s.warmup).flatMap(s=>s.sides.filter(a=>a.done)));if(!done.length)return '';const volumes=records.map(r=>r.ex.sets.filter(s=>!s.warmup).reduce((n,s)=>n+s.sides.filter(a=>a.done).reduce((m,a)=>m+a.weight*a.reps,0),0)).slice(-12),max=Math.max(...volumes,1);return `<section class="card"><h2>${ex.name}</h2><p>${(ex.unilateral?['Left','Right']:['Both']).map(side=>{const arms=done.filter(a=>a.side===side);if(!arms.length)return `${side}: no completed sets`;const weight=Math.max(...arms.map(a=>a.weight)),reps=Math.max(...arms.filter(a=>a.weight===weight).map(a=>a.reps));return `${side==='Both'?'Best set':side+ ' best'}: <strong>${weight} kg × ${reps}</strong>`;}).join('<br>')}</p><div class="chart" role="img" aria-label="Completed volume over the last ${volumes.length} sessions: ${volumes.join(', ')} kilogram reps">${volumes.map(v=>`<span class="bar" style="height:${Math.max(3,v/max*100)}%" title="${v} kg reps"></span>`).join('')}</div><small>Completed volume (kg × reps) · oldest to newest</small><details><summary>View progression</summary>${records.map(r=>`<p class="muted">${date(r.date)} · ${r.ex.sets.filter(s=>!s.warmup).flatMap(s=>s.sides.filter(a=>a.done).map(a=>`${a.side==='Both'?'':a.side+' '}${a.weight} kg × ${a.reps}`)).join(' · ')||'No completed sets'}</p>`).join('')}</details></section>`;}).join('');app.innerHTML=`<div class="eyebrow">Build on your last session</div><h1>Progress</h1><p class="muted">Personal bests use completed working sets. Warm-ups are excluded.</p>${list||'<p class="empty">Complete a workout to see your personal bests and training volume over time.</p>'}`;}
function renderSettings(){app.innerHTML=`<div class="eyebrow">Make it yours</div><h1>Settings</h1><section class="card"><h2>Rest durations</h2><p class="muted">Seconds, from 15 to 900. Changes apply to the next completed set.</p>${programme.flat().map(e=>`<label class="setting"><span>${e.name}</span><input aria-label="${e.name} rest seconds" type="number" inputmode="numeric" min="15" max="900" step="1" value="${state.settings.rest[e.id]??e.rest}" data-rest="${e.id}"></label>`).join('')}</section><section class="card"><h2>Your data, your device</h2><p class="muted">Export backups regularly. Clearing Safari website data or changing devices can remove your history. Import replaces the data on this device.</p><button id="export">Export backup</button><label class="file">Import backup <input id="import" type="file" accept="application/json,.json"></label></section><section class="card"><h2>Install on iPhone</h2><p>Open the published app in Safari, tap Share, then Add to Home Screen. Open it once while online to make it available offline.</p><p class="muted">Sound needs a tap in the app first. iPhone may silence alerts when the app is in the background or the phone is locked; the countdown catches up when you return. Vibration is used only where supported.</p><button id="sound">Test rest alert</button></section>`;}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));({workout:renderWorkout,history:renderHistory,progress:renderProgress,settings:renderSettings})[view]();renderTimer();}
function changeDay(n){day=(n+4)%4;if(state.drafts[day]){state.activeDay=day;save();}render();}
function end(){const next=finish(state,day);day=state.activeDay??next;save();document.querySelector('#confirm').close();render();window.scrollTo(0,0);notice(`Workout saved. Day ${next+1} is next.`);}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;unlockAudio();if(b.dataset.view){view=b.dataset.view;render();window.scrollTo(0,0);}if(b.dataset.day!==undefined)changeDay(+b.dataset.day);
 if(b.dataset.complete){const [ei,si,ai]=b.dataset.complete.split(',').map(Number),s=begin(),ex=s.exercises[ei],set=ex.sets[si],arm=set.sides[ai];if(!arm.done&&(arm.weight===''||!Number.isFinite(arm.weight)||!Number.isInteger(arm.reps))){notice('Enter a weight and whole number of reps first.');return;}arm.done=!arm.done;if(complete(set))startTimer(ex);save();render();}
 if(b.dataset.warmup!==undefined){const ex=begin().exercises[+b.dataset.warmup];ex.sets.push({warmup:true,sides:(ex.unilateral?['Left','Right']:['Both']).map(side=>({side,weight:'',reps:ex.reps,done:false}))});save();render();}
 if(b.id==='finish'){begin();save();if(count(state.drafts[day])<total(state.drafts[day]))document.querySelector('#confirm').showModal();else end();}
 if(b.id==='keep')document.querySelector('#confirm').close();if(b.id==='early')end();
 if(b.dataset.timer&&state.timer){const t=state.timer,action=b.dataset.timer;if(action==='dismiss')state.timer=null;if(action==='pause'){t.remaining=remaining(t);t.paused=!t.paused;t.endsAt=Date.now()+t.remaining*1000;}if(action==='restart'){t.remaining=t.duration;t.endsAt=Date.now()+t.duration*1000;t.paused=false;delete t.alerted;}if(action==='add'){t.remaining=remaining(t)+30;t.endsAt=Date.now()+t.remaining*1000;delete t.alerted;}save();renderTimer();}
 if(b.id==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`form-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(b.id==='sound')setTimeout(alertRest,150);
});
app.addEventListener('change',async event=>{const input=event.target;if(input.dataset.field){const n=Number(input.value),field=input.dataset.field;if((input.value===''&&field==='reps')||!input.checkValidity()||!Number.isFinite(n)){notice('Use a valid non-negative weight or whole number of reps.');render();return;}const [ei,si,ai]=input.dataset.pos.split(',').map(Number);begin().exercises[ei].sets[si].sides[ai][field]=input.value===''?'':n;if(input.value==='')state.drafts[day].exercises[ei].sets[si].sides[ai].done=false;save();}if(input.dataset.rest){if(!input.checkValidity()||input.value===''){notice('Choose a rest duration from 15 to 900 seconds.');render();return;}state.settings.rest[input.dataset.rest]=Number(input.value);save();}if(input.id==='import'&&input.files[0]){try{if(input.files[0].size>20e6)throw Error('Backup is too large (maximum 20 MB).');const imported=validate(JSON.parse(await input.files[0].text()));if(!window.confirm('Replace all workouts and settings on this device with this backup?'))return;localStorage.setItem(KEY,JSON.stringify(imported));state=imported;storageOK=true;day=state.activeDay??state.nextDay;render();notice('Backup restored.');}catch(error){notice(error.message||'Could not import this backup.');}}});
app.addEventListener('input',event=>{const input=event.target;if(!input.dataset.field||!input.checkValidity()||input.value==='')return;const [ei,si,ai]=input.dataset.pos.split(',').map(Number);begin().exercises[ei].sets[si].sides[ai][input.dataset.field]=Number(input.value);save();});
let touch;app.addEventListener('touchstart',e=>{if(view==='workout'&&!e.target.closest('input,button'))touch={x:e.touches[0].clientX,y:e.touches[0].clientY};else touch=null;},{passive:true});app.addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)changeDay(day+(dx<0?1:-1));touch=null;},{passive:true});
setInterval(()=>{if(state.timer){if(remaining(state.timer)===0&&!state.timer.paused&&!state.timer.alerted){state.timer.alerted=true;alertRest();save();}renderTimer();}},250);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)renderTimer();});
render();if(!storageOK)notice('Saved data could not be read. It has not been overwritten. Restore a backup in Settings.');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>notice('Offline setup failed. Reopen while online to try again.'));

if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_workout',description:'Read the displayed workout day and working-set completion.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({day:day+1,completed:count(session()),total:total(session())})},{name:'select_workout_day',description:'Display a workout day without completing or discarding any sets.',inputSchema:{type:'object',properties:{day:{type:'integer',minimum:1,maximum:4}},required:['day'],additionalProperties:false},execute:input=>{if(!Number.isInteger(input?.day)||input.day<1||input.day>4)throw Error('Day must be 1 through 4');view='workout';changeDay(input.day-1);return {day:day+1};}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
